### PR TITLE
Draft submission narrative

### PR DESCRIPTION
**Pull request by rross0**
This PR creates a submission narrative for this repository. 

@colegreene the Transit Narrative... .Rmd file generates the .docx submission. This repository is currently public. I reviewed and updated all code and analysis language. I also anonymized operator IDs using a hash.

### CODE REVIEW

**Comment by rross0** [comment]
@colegreene bumping this because I almost forgot to roll it into 12.

**Comment by colegreene** [comment]
@rross0 - being a GitHub novice, can you please link the competition submission word doc or share a link that will direct me to it? Thanks,

**Comment by rross0** [comment]
@colegreene  https://github.com/MTA-MD-OPM/mta_trb_data_challenge_2025_submission

**Comment by colegreene** [comment]
@rross0 - this is what I see when I click the link. Can you guide me to the word document?
image

**Comment by rross0** [comment]
Whoops. I'm not doing great on the link copying. Click the file "Effect-of-Live-Texts" and on the next page look for the download button (downward facing arrow) near the top-right of the subwindow.

**Comment by colegreene** [comment]
Got it, thanks!

**Comment by rross0** [comment]
@colegreene merging and submitting.

**Comment by colegreene** [comment]
@rross0 - thanks I could not locate a word document version.

**Pull request merged**
